// flow-typed signature: d07394fc57754428a123435602229822
// flow-typed version: <<STUB>>/tape-catch_v^1.0.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape-catch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape-catch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tape-catch/bin/copy-tape-tests' {
  declare module.exports: any;
}

declare module 'tape-catch/bin/install-tape-deps' {
  declare module.exports: any;
}

declare module 'tape-catch/chain' {
  declare module.exports: any;
}

declare module 'tape-catch/example' {
  declare module.exports: any;
}

declare module 'tape-catch/manager' {
  declare module.exports: any;
}

declare module 'tape-catch/syntax-error.es2015' {
  declare module.exports: any;
}

declare module 'tape-catch/syntax-error.eval' {
  declare module.exports: any;
}

declare module 'tape-catch/syntax-error' {
  declare module.exports: any;
}

declare module 'tape-catch/test/catch-exceptions' {
  declare module.exports: any;
}

declare module 'tape-catch/test/catch-exceptions/catch-harness' {
  declare module.exports: any;
}

declare module 'tape-catch/test/catch-exceptions/catch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tape-catch/bin/copy-tape-tests.js' {
  declare module.exports: $Exports<'tape-catch/bin/copy-tape-tests'>;
}
declare module 'tape-catch/bin/install-tape-deps.js' {
  declare module.exports: $Exports<'tape-catch/bin/install-tape-deps'>;
}
declare module 'tape-catch/chain.js' {
  declare module.exports: $Exports<'tape-catch/chain'>;
}
declare module 'tape-catch/example.js' {
  declare module.exports: $Exports<'tape-catch/example'>;
}
declare module 'tape-catch/index' {
  declare module.exports: $Exports<'tape-catch'>;
}
declare module 'tape-catch/index.js' {
  declare module.exports: $Exports<'tape-catch'>;
}
declare module 'tape-catch/manager.js' {
  declare module.exports: $Exports<'tape-catch/manager'>;
}
declare module 'tape-catch/syntax-error.es2015.js' {
  declare module.exports: $Exports<'tape-catch/syntax-error.es2015'>;
}
declare module 'tape-catch/syntax-error.eval.js' {
  declare module.exports: $Exports<'tape-catch/syntax-error.eval'>;
}
declare module 'tape-catch/syntax-error.js' {
  declare module.exports: $Exports<'tape-catch/syntax-error'>;
}
declare module 'tape-catch/test/catch-exceptions.js' {
  declare module.exports: $Exports<'tape-catch/test/catch-exceptions'>;
}
declare module 'tape-catch/test/catch-exceptions/catch-harness.js' {
  declare module.exports: $Exports<'tape-catch/test/catch-exceptions/catch-harness'>;
}
declare module 'tape-catch/test/catch-exceptions/catch.js' {
  declare module.exports: $Exports<'tape-catch/test/catch-exceptions/catch'>;
}
